### ISSUE TITLE
systemd does not work

### ISSUE THREAD

**Issue by WWebber** [virtualzone/landroid-bridge#53]
```
landroid-bridge[26265]: /home/user1/landroid-bridge/node_modules/log4js/lib/layouts.js:69
landroid-bridge[26265]:   ) + util.format(...loggingEvent.data);
landroid-bridge[26265]:                   ^^^
landroid-bridge[26265]: SyntaxError: Unexpected token ...

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user1/landroid-bridge/node_modules/log4js/lib/log4js.js:27:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by WWebber** [comment]
SOLVED!!
The ExecStart path had to be changed! The proper 'nodejs' was not under /usr/bin/ !!
