### ISSUE TITLE
bad config? no schedule ahead

### ISSUE THREAD

**Issue by iz3man** [virtualzone/landroid-bridge#64]
I kindly ask someone to check my config, as i don't see any planned mowing activity in my schedule. Even though it's not raining and i set mowing to 7 days a week nothing happens.
Any ideas very welcome!

![image](https://user-images.githubusercontent.com/11553674/58372641-01a8d180-7f21-11e9-863d-acff8ef9019e.png)

And this is my config.json file:

```
{
    "http": {
        "port": 3000
    },
    "landroid-s": {
        "enable": true,
        "email": "xxxxxxx",
        "pwd": "xxxxxxx",
        "dev_sel": 0
    },
    "mqtt": {
        "enable": true,
        "url": "xxxxxxxxxx@localhost",
        "topic": "landroid"
    },
    "logLevel": "info",
    "scheduler": {
        "enable": true,
        "cron": true,
        "weather": {
            "provider": "darksky",
            "apiKey": "219389ca143fa62xxxxxxxxx",
            "latitude": xxxxxxxx,
            "longitude": xxxxxxx
        },
        "db": "./scheduler.db",
        "earliestStart": 14,
        "latestStop": 20,
        "startEarly": true,
        "offDays": 0,
        "squareMeters": 60,
        "perHour": 15,
        "mowTime": 75,
        "chargeTime": 75,
        "daysForTotalCut": 7,
        "rainDelay": 180,
        "threshold": 30
    }
}
```

**Comment by charlez79** [comment]
Same issue here, running docker container.

Logs show these error.

[2019-05-28T17:10:31.950] [INFO] ScheduledTasks - Successfully refreshed weather cache
[2019-05-28T17:15:00.007] [INFO] ScheduledTasks - Running ScheduledTasks.applySchedule...
[2019-05-28T17:15:00.117] [ERROR] App - Unhandled rejection: Error: Could not load weather forecast: TypeError: Cannot read property 'dateTime' of undefined
[2019-05-28T17:55:24.800] [ERROR] SchedulerRouter - Error: Could not load weather forecast: TypeError: Cannot read property 'dateTime' of undefined
    at WeatherFactory_1.WeatherFactory.getProvider.loadHourly10day.then.catch.e (/usr/src/app/dist/Scheduler.js:60:34)
[2019-05-28T18:10:30.017] [INFO] ScheduledTasks - Refreshing weather to cache (try #1)...
[2019-05-28T18:10:30.019] [INFO] WeatherDarkSky - Loading from https://api.darksky.net/forecast/75f2941bdc55310317f3edf5ac2d3e15/51.194106,4.5594391?units=si
[2019-05-28T18:10:30.722] [INFO] WeatherDarkSky - Loading from https://api.darksky.net/forecast/75f2xxxxxxxxf3edf5ac2d3e15/51.194106,xxx3xxxxxx01630?units=si
[2019-05-28T18:10:31.238] [INFO] WeatherDarkSky - Loading from https://api.darksky.net/forecast/75f2xxxxxxxxdf5ac2d3e15/xxxx194106,xxxxxx91?units=si
[2019-05-28T18:10:31.969] [INFO] ScheduledTasks - Successfully refreshed weather cache
[2019-05-28T18:15:00.007] [INFO] ScheduledTasks - Running ScheduledTasks.applySchedule...
[2019-05-28T18:15:00.079] [ERROR] App - Unhandled rejection: Error: Could not load weather forecast: TypeError: Cannot read property 'dateTime' of undefined
[2019-05-28T18:45:49.052] [ERROR] SchedulerRouter - Error: Could not load weather forecast: TypeError: Cannot read property 'dateTime' of undefined
    at WeatherFactory_1.WeatherFactory.getProvider.loadHourly10day.then.catch.e (/usr/src/app/dist/Scheduler.js:60:34)
[2019-05-28T18:58:28.507] [ERROR] SchedulerRouter - Error: Could not load weather forecast: TypeError: Cannot read property 'dateTime' of undefined
    at WeatherFactory_1.WeatherFactory.getProvider.loadHourly10day.then.catch.e (/usr/src/app/dist/Scheduler.js:60:34)

**Comment by xpx** [comment]
I'm also seeing this issue

**Comment by Crazyachmed** [comment]
I can see the exact same error in my log. Unfortunatly I cannot try it out with the wunderground-API as it requires you to have your own station now.

`
[2019-06-30T10:58:07.171] [ERROR] SchedulerRouter - Error: Could not load weather forecast: TypeError: Cannot read property 'dateTime' of undefined


    at WeatherFactory_1.WeatherFactory.getProvider.loadHourly10day.then.catch.e (/usr/src/app/dist/Scheduler.js:60:34)`

**Comment by iz3man** [comment]
You can use openweather.org as well

**Comment by charlez79** [comment]
openweather.org is so unaccurate

**Comment by Crazyachmed** [comment]
There aren't any other weather providers possible according to src/WeatherFactory.ts

**Comment by andenmad** [comment]
hi i have same issue anyone found a solution?

**Comment by kdrost1** [comment]
Same issue here, would like to hear if anybody found a solution, i'm using Darksky
