### ISSUE TITLE
DDoS - Could not finish initialization, retrying... retrying... retrying... retrying... retrying... 

### ISSUE THREAD

**Issue by nicoh88** [virtualzone/landroid-bridge#86]
_Sorry, ich muss das Issue in Deutsch schreiben - zu komplex - die Entwickler sind ja aus Deutschland. 👍_ 

@virtualzone @mkoetzing @RolandRosenfeld 

Ich habe vor ein paar Tagen meinen Landroid WR141E ausgeschaltet und zur Überwinterung eingemottet. Ein paar Tage später bekam ich Probleme mit meiner FRITZ!Box, diese stürzt im 15 Minuten Takt ab... 
Da das originale Vodafone / Kabel Deutschland Gerät besser funktionierte, machte ich eine Störung auf, da ich dachte, dass am Kabel-Anschluss Störsignale ankommen. 
Techniker war da, konnte keine Kabel-Störung feststellen. Er bemerkte lediglich, dass wenn er mein "_Master_" Netzwerkkabel, welche alle Geräte im Haus mit dem Router verbindet, mit dem Router verbunden hat, er keine Leitungsmessung mehr durchführen konnten. Mit einem Austausch-Gerät ging es dann - logisch, da meine Geräte teilweise fixe IP's haben und nicht im Standard-Netzwerkadressebereich arbeiten ... sobald ich dem neuen Router dann die richtigen Netzwerkeinstellungen spendiert habe, gingen die Probleme wieder los.
Deshalb machte ich mich dann auf die Suche nach dem Problem im eigenen Netzwerk - ich vermutete, dass ein Gerät oder Dienst meinen Router mit sehr vielen Anfragen (_DDoS-Mäßig_) in die Knie zwingt. 

Übeltäter scheint die `landroid-bridge` zu sein, die nach ein paar Stunden, wenn die Bridge keine Verbindung aufbauen konnte, ca. 20-40 DNS-Abfragen, es werden immer mehr und mehr, in der SEKUNDE und damit verbunden Verbindungsversuche unternimmt und den Router nach einiger Zeit zur Aufgabe zwingt.

Keine Ahnung warum, scheint ein Bug zu sein. Laut der Log im `systemd` versucht er es nur einmal jede Minute, meine Pi-Hole, welche die DNS-Querys überwacht, sagt etwas anderes.

Wäre nice, wenn ihr das fixen könntet. 🤣 

<img width="1015" alt="Bildschirmfoto 2019-11-11 um 22 41 33" src="https://user-images.githubusercontent.com/264264/68623295-72927480-04d4-11ea-870d-89b985e721b5.png">

<img width="1085" alt="Bildschirmfoto 2019-11-11 um 19 42 51" src="https://user-images.githubusercontent.com/264264/68621149-4fb19180-04cf-11ea-86f3-c5106c8e54e9.png">

<img width="623" alt="Bildschirmfoto 2019-11-11 um 20 01 49" src="https://user-images.githubusercontent.com/264264/68621162-56400900-04cf-11ea-9ff4-d8ad80c87bca.png">

```
Nov 11 19:15:30 frida node[458]: [2019-11-11T19:15:30.679] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:16:29 frida node[458]: [2019-11-11T19:16:29.031] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:16:29 frida node[458]: Mqtt url: undefined
Nov 11 19:16:30 frida node[458]: [2019-11-11T19:16:30.767] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:17:29 frida node[458]: [2019-11-11T19:17:29.049] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:17:29 frida node[458]: Mqtt url: undefined
Nov 11 19:17:30 frida node[458]: [2019-11-11T19:17:30.462] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:18:29 frida node[458]: [2019-11-11T19:18:29.049] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:18:29 frida node[458]: Mqtt url: undefined
Nov 11 19:18:30 frida node[458]: [2019-11-11T19:18:30.639] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:19:29 frida node[458]: [2019-11-11T19:19:29.050] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:19:29 frida node[458]: Mqtt url: undefined
Nov 11 19:19:30 frida node[458]: [2019-11-11T19:19:30.565] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:20:29 frida node[458]: [2019-11-11T19:20:29.106] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:20:30 frida node[458]: Mqtt url: undefined
Nov 11 19:20:30 frida node[458]: [2019-11-11T19:20:30.821] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:21:29 frida node[458]: [2019-11-11T19:21:29.106] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:21:30 frida node[458]: Mqtt url: undefined
Nov 11 19:21:30 frida node[458]: [2019-11-11T19:21:30.657] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:22:29 frida node[458]: [2019-11-11T19:22:29.189] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:22:30 frida node[458]: Mqtt url: undefined
Nov 11 19:22:30 frida node[458]: [2019-11-11T19:22:30.924] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:23:29 frida node[458]: [2019-11-11T19:23:29.190] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:23:31 frida node[458]: Mqtt url: undefined
Nov 11 19:23:33 frida node[458]: [2019-11-11T19:23:33.566] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:24:29 frida node[458]: [2019-11-11T19:24:29.196] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:24:30 frida node[458]: Mqtt url: undefined
Nov 11 19:24:30 frida node[458]: [2019-11-11T19:24:30.848] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:25:05 frida node[458]: [2019-11-11T19:25:05.374] [ERROR] App - Unhandled exception: TypeError: Cannot read property 'log' of undefined
Nov 11 19:25:05 frida node[458]:     at MqttClient.<anonymous> (/opt/landroid-bridge/node_modules/iobroker.landroid-s/lib/mqttCloud.js:199:22)
Nov 11 19:25:05 frida node[458]:     at MqttClient.emit (events.js:210:5)
Nov 11 19:25:05 frida node[458]:     at TLSSocket.handleTLSerrors (/opt/landroid-bridge/node_modules/mqtt/lib/connect/tls.js:26:18)
Nov 11 19:25:05 frida node[458]:     at TLSSocket.emit (events.js:215:7)
Nov 11 19:25:05 frida node[458]:     at emitErrorNT (internal/streams/destroy.js:92:8)
Nov 11 19:25:05 frida node[458]:     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Nov 11 19:25:05 frida node[458]:     at processTicksAndRejections (internal/process/task_queues.js:80:21)
Nov 11 19:25:05 frida node[458]: [2019-11-11T19:25:05.376] [ERROR] App - Unhandled exception: TypeError: Cannot read property 'log' of undefined
Nov 11 19:25:05 frida node[458]:     at MqttClient.<anonymous> (/opt/landroid-bridge/node_modules/iobroker.landroid-s/lib/mqttCloud.js:199:22)
Nov 11 19:25:05 frida node[458]:     at MqttClient.emit (events.js:210:5)
Nov 11 19:25:05 frida node[458]:     at TLSSocket.handleTLSerrors (/opt/landroid-bridge/node_modules/mqtt/lib/connect/tls.js:26:18)
Nov 11 19:25:05 frida node[458]:     at TLSSocket.emit (events.js:215:7)
Nov 11 19:25:05 frida node[458]:     at emitErrorNT (internal/streams/destroy.js:92:8)
Nov 11 19:25:05 frida node[458]:     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Nov 11 19:25:05 frida node[458]:     at processTicksAndRejections (internal/process/task_queues.js:80:21)
Nov 11 19:25:15 frida node[458]: [2019-11-11T19:25:15.381] [ERROR] App - Unhandled exception: TypeError: Cannot read property 'log' of undefined
Nov 11 19:25:15 frida node[458]:     at MqttClient.<anonymous> (/opt/landroid-bridge/node_modules/iobroker.landroid-s/lib/mqttCloud.js:199:22)
Nov 11 19:25:15 frida node[458]:     at MqttClient.emit (events.js:210:5)
Nov 11 19:25:15 frida node[458]:     at TLSSocket.handleTLSerrors (/opt/landroid-bridge/node_modules/mqtt/lib/connect/tls.js:26:18)
Nov 11 19:25:15 frida node[458]:     at TLSSocket.emit (events.js:215:7)
Nov 11 19:25:15 frida node[458]:     at emitErrorNT (internal/streams/destroy.js:92:8)
Nov 11 19:25:15 frida node[458]:     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Nov 11 19:25:15 frida node[458]:     at processTicksAndRejections (internal/process/task_queues.js:80:21)
Nov 11 19:25:15 frida node[458]: [2019-11-11T19:25:15.382] [ERROR] App - Unhandled exception: TypeError: Cannot read property 'log' of undefined
Nov 11 19:25:15 frida node[458]:     at MqttClient.<anonymous> (/opt/landroid-bridge/node_modules/iobroker.landroid-s/lib/mqttCloud.js:199:22)
Nov 11 19:25:15 frida node[458]:     at MqttClient.emit (events.js:210:5)
Nov 11 19:25:15 frida node[458]:     at TLSSocket.handleTLSerrors (/opt/landroid-bridge/node_modules/mqtt/lib/connect/tls.js:26:18)
Nov 11 19:25:15 frida node[458]:     at TLSSocket.emit (events.js:215:7)
Nov 11 19:25:15 frida node[458]:     at emitErrorNT (internal/streams/destroy.js:92:8)
Nov 11 19:25:15 frida node[458]:     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Nov 11 19:25:15 frida node[458]:     at processTicksAndRejections (internal/process/task_queues.js:80:21)
Nov 11 19:25:30 frida node[458]: [2019-11-11T19:25:30.957] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:25:46 frida node[458]: Mqtt url: undefined
Nov 11 19:25:58 frida node[458]: [2019-11-11T19:25:58.592] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:26:03 frida node[458]: [2019-11-11T19:26:03.742] [ERROR] App - Unhandled exception: TypeError: Cannot read property 'log' of undefined
Nov 11 19:26:03 frida node[458]:     at MqttClient.<anonymous> (/opt/landroid-bridge/node_modules/iobroker.landroid-s/lib/mqttCloud.js:199:22)
Nov 11 19:26:03 frida node[458]:     at MqttClient.emit (events.js:210:5)
Nov 11 19:26:03 frida node[458]:     at TLSSocket.handleTLSerrors (/opt/landroid-bridge/node_modules/mqtt/lib/connect/tls.js:26:18)
Nov 11 19:26:03 frida node[458]:     at TLSSocket.emit (events.js:215:7)
Nov 11 19:26:03 frida node[458]:     at emitErrorNT (internal/streams/destroy.js:92:8)
Nov 11 19:26:03 frida node[458]:     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Nov 11 19:26:03 frida node[458]:     at processTicksAndRejections (internal/process/task_queues.js:80:21)
Nov 11 19:26:08 frida node[458]: [2019-11-11T19:26:08.741] [ERROR] App - Unhandled exception: TypeError: Cannot read property 'log' of undefined
Nov 11 19:26:08 frida node[458]:     at MqttClient.<anonymous> (/opt/landroid-bridge/node_modules/iobroker.landroid-s/lib/mqttCloud.js:199:22)
Nov 11 19:26:08 frida node[458]:     at MqttClient.emit (events.js:210:5)
Nov 11 19:26:08 frida node[458]:     at TLSSocket.handleTLSerrors (/opt/landroid-bridge/node_modules/mqtt/lib/connect/tls.js:26:18)
Nov 11 19:26:08 frida node[458]:     at TLSSocket.emit (events.js:215:7)
Nov 11 19:26:08 frida node[458]:     at emitErrorNT (internal/streams/destroy.js:92:8)
Nov 11 19:26:08 frida node[458]:     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Nov 11 19:26:08 frida node[458]:     at processTicksAndRejections (internal/process/task_queues.js:80:21)
Nov 11 19:26:13 frida node[458]: [2019-11-11T19:26:13.756] [ERROR] App - Unhandled exception: TypeError: Cannot read property 'log' of undefined
Nov 11 19:26:13 frida node[458]:     at MqttClient.<anonymous> (/opt/landroid-bridge/node_modules/iobroker.landroid-s/lib/mqttCloud.js:199:22)
Nov 11 19:26:13 frida node[458]:     at MqttClient.emit (events.js:210:5)
Nov 11 19:26:13 frida node[458]:     at TLSSocket.handleTLSerrors (/opt/landroid-bridge/node_modules/mqtt/lib/connect/tls.js:26:18)
Nov 11 19:26:13 frida node[458]:     at TLSSocket.emit (events.js:215:7)
Nov 11 19:26:13 frida node[458]:     at emitErrorNT (internal/streams/destroy.js:92:8)
Nov 11 19:26:13 frida node[458]:     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Nov 11 19:26:13 frida node[458]:     at processTicksAndRejections (internal/process/task_queues.js:80:21)
Nov 11 19:26:31 frida node[458]: [2019-11-11T19:26:31.499] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:26:44 frida node[458]: Mqtt url: undefined
Nov 11 19:26:55 frida node[458]: [2019-11-11T19:26:55.779] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:27:31 frida node[458]: [2019-11-11T19:27:31.501] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:27:32 frida node[458]: Mqtt url: undefined
Nov 11 19:27:32 frida node[458]: [2019-11-11T19:27:32.869] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:28:31 frida node[458]: [2019-11-11T19:28:31.627] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:28:33 frida node[458]: Mqtt url: undefined
Nov 11 19:28:34 frida node[458]: [2019-11-11T19:28:34.333] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:29:31 frida node[458]: [2019-11-11T19:29:31.810] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:29:33 frida node[458]: Mqtt url: undefined
Nov 11 19:29:35 frida node[458]: [2019-11-11T19:29:35.485] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:30:31 frida node[458]: [2019-11-11T19:30:31.819] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:30:32 frida node[458]: Mqtt url: undefined
Nov 11 19:30:34 frida node[458]: [2019-11-11T19:30:34.650] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:31:31 frida node[458]: [2019-11-11T19:31:31.820] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:31:32 frida node[458]: Mqtt url: undefined
Nov 11 19:31:34 frida node[458]: [2019-11-11T19:31:34.038] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:32:31 frida node[458]: [2019-11-11T19:32:31.820] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:32:32 frida node[458]: Mqtt url: undefined
Nov 11 19:32:33 frida node[458]: [2019-11-11T19:32:33.485] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:33:31 frida node[458]: [2019-11-11T19:33:31.840] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:33:32 frida node[458]: Mqtt url: undefined
Nov 11 19:33:33 frida node[458]: [2019-11-11T19:33:33.446] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:34:31 frida node[458]: [2019-11-11T19:34:31.841] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:34:32 frida node[458]: Mqtt url: undefined
Nov 11 19:34:33 frida node[458]: [2019-11-11T19:34:33.219] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:35:31 frida node[458]: [2019-11-11T19:35:31.842] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:35:32 frida node[458]: Mqtt url: undefined
Nov 11 19:35:33 frida node[458]: [2019-11-11T19:35:33.184] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:36:31 frida node[458]: [2019-11-11T19:36:31.842] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:36:32 frida node[458]: Mqtt url: undefined
Nov 11 19:36:33 frida node[458]: [2019-11-11T19:36:33.246] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:37:31 frida node[458]: [2019-11-11T19:37:31.842] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:37:32 frida node[458]: Mqtt url: undefined
Nov 11 19:37:33 frida node[458]: [2019-11-11T19:37:33.233] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:38:31 frida node[458]: [2019-11-11T19:38:31.843] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:38:32 frida node[458]: Mqtt url: undefined
Nov 11 19:38:33 frida node[458]: [2019-11-11T19:38:33.272] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:39:31 frida node[458]: [2019-11-11T19:39:31.842] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:39:32 frida node[458]: Mqtt url: undefined
Nov 11 19:39:33 frida node[458]: [2019-11-11T19:39:33.221] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:40:31 frida node[458]: [2019-11-11T19:40:31.843] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:40:33 frida node[458]: Mqtt url: undefined
Nov 11 19:40:33 frida node[458]: [2019-11-11T19:40:33.848] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:41:31 frida node[458]: [2019-11-11T19:41:31.843] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:41:32 frida node[458]: Mqtt url: undefined
Nov 11 19:41:33 frida node[458]: [2019-11-11T19:41:33.175] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:42:31 frida node[458]: [2019-11-11T19:42:31.847] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:42:32 frida node[458]: Mqtt url: undefined
Nov 11 19:42:33 frida node[458]: [2019-11-11T19:42:33.507] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:43:31 frida node[458]: [2019-11-11T19:43:31.871] [INFO] LandroidS - Could not finish initialization, retrying...
Nov 11 19:43:32 frida node[458]: Mqtt url: undefined
Nov 11 19:43:33 frida node[458]: [2019-11-11T19:43:33.673] [INFO] IoBrokerAdapter - mower 0 selected
Nov 11 19:43:58 frida systemd[1]: Stopping Landroid Bridge...
Nov 11 19:43:58 frida node[458]: [2019-11-11T19:43:58.479] [INFO] App - Received exit signal...
Nov 11 19:43:58 frida node[458]: [2019-11-11T19:43:58.480] [INFO] App - Closing http listener...
Nov 11 19:43:58 frida systemd[1]: landroid-bridge.service: Succeeded.
Nov 11 19:43:58 frida systemd[1]: Stopped Landroid Bridge.
```

**Comment by rosscullen** [comment]
I've been having the same issue. I put my Landroid away for the winter as well. After a few days, my internet connection was slow. Turns out the Landroid-bridge Docker Container was hogging all the WAN bandwidth. I didn't have time to analyse the traffic. I've since shut down the container.

**Comment by SDeath667** [comment]
Same issue here, shutdown for the winter and a lot of DNS requests from the bridge.
About 1/3 of all DNS requests in my network comes from the bridge.

**Comment by hagor** [comment]
I can confirm this issue, my DNS server is flooded with requests from the bridge.

**Comment by SDeath667** [comment]
After restaring everything after winter season I still have the same problem and the bridge status page gives me a “Internal Server Error”. 
Can this be fixed?
Or is the Landroid API changed that the bridge uses?

**Comment by hagor** [comment]
@SDeath667 Debug shows, that Information is still comming in, so no changes on the Landroid API
Your problem seems to have other reasons so a separate issue might make sense.

**Comment by DonStefano** [comment]
Same problem here. I have shut down landroid bridge until spring.

**Comment by SDeath667** [comment]
> @SDeath667 Debug shows, that Information is still comming in, so no changes on the Landroid API
> Your problem seems to have other reasons so a separate issue might make sense.

I will try a fresh install of the VM and bridge first.

**Comment by int5749** [comment]
:-/  looks like support for bridge has been stopped, as nobody replies to issues :-(

**Comment by NuKeMtje** [comment]
Thank you for this information, if I only knew sooner it would have saved me a 150€ ISP service visit :)
I’m running pfSense (also for DNS) with a WAN PPPoE connection to a FritzBox. After some time (3-4 days or more) my internet connection became unusable (very high / timed out and unstable pings), also on a separate FritzBox network with its own PPPoE connection, the FritzBox reported lots of internet cleared and reconnects, so I was suspecting my VDSL connection or ISP as nothing changed in my network. 
But, when disconnecting my pfSense router thus disconnecting the system running the Landroid bridge, everything on the FritzBox returned to normal.
So each time the problem occurred I started restarting and disconnecting systems and finally arrived at restarting the Landroid bridge service which seamed to cause the problem. (I guess I should have run a packet capture and analysed the data in WireShark instead to be faster like you did). 
So now here we are :) I hope this can be fixed.

**Comment by virtualzone** [comment]
Should be fixed with the latest commit

**Comment by theWaldschrat** [comment]
One last comment: It could also be caused by being blocked due to using the old API. If you have updated to the new API and still get this, wait 24 hours and try again.

**Comment by SDeath667** [comment]
How would you upgrade to the new api?

**Comment by theWaldschrat** [comment]
If you build the bridge yourself from sources, just pull the newest version and build it, it has been fixed in one of the latest commits.
If you're using some pre-build version (docker...) you have to wait for the maintainer to update.

**Comment by SDeath667** [comment]
Ok I did a fresh build from the sources yesterday so should be fine. 
I do see a tremendous amount of DNS traffic coming from the bridge.

**Comment by JakobTewes** [comment]
Had an unresponsive router too. Issue still exists with lastest version?!

**Comment by holgerpieta** [comment]
I've been using my own image that I created while fixing that, so I didn't try. Now I tried and the answer is: No, it doesn't work.
I cannot reopen this issue, so let's make a new one: #100

**Comment by holgerpieta** [comment]
See other ticket: Images need to be recreated.

**Comment by holgerpieta** [comment]
Fixed by @virtualzone by recreating the images after fixing a build problem with git.

I tried the arm32v7 image and it works.
