### ISSUE TITLE
App - Unhandled exception: TypeError: Cannot read property 'log' of undefined

### ISSUE THREAD

**Issue by merlin2533** [virtualzone/landroid-bridge#97]
When i try to use the latest docker

[2020-04-15T20:12:34.389] [INFO] server.ts - Starting Landroid Bridge...
[2020-04-15T20:12:34.409] [INFO] server.ts - Setting port to 3000...
[2020-04-15T20:12:34.413] [INFO] Mqtt - MQTT is disabled, skipping initialization
[2020-04-15T20:12:34.426] [INFO] App - Adding static files path /usr/src/app/www
[2020-04-15T20:12:34.431] [INFO] Scheduler - Creating SQLite database at /usr/src/app/scheduler.db
[2020-04-15T20:12:34.459] [INFO] LandroidS - Initializing Landroid Cloud Service...
[2020-04-15T20:12:34.688] [ERROR] App - Unhandled exception: TypeError: Cannot read property 'log' of undefined

    at ClientRequest.<anonymous> (/usr/src/app/node_modules/iobroker.landroid-s/lib/mqttCloud.js:280:22)

    at ClientRequest.emit (events.js:310:20)

    at TLSSocket.socketErrorListener (_http_client.js:426:9)

    at TLSSocket.emit (events.js:310:20)

    at emitErrorNT (internal/streams/destroy.js:92:8)

    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)

    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by ciechompl** [comment]
i have the same ... and still open issue here: https://github.com/virtualzone/landroid-bridge/issues/38

**Comment by ciechompl** [comment]
only 2 of us have this issue ? no one else ?  :(

**Comment by virtualzone** [comment]
Seems to be an issue in the used library (iobroker.landroid-s/lib/mqttCloud.js), can't fix this in the bridge.

**Comment by CoolID2** [comment]
Hi,
I´ve got the same error.
Are there any news about that issue?
